- name: Update Controller Job Template Survey Options
  hosts: localhost
  gather_facts: false

  tasks: 
    
    - name: Update job_template survey
      ansible.controller.job_template:
        name: "COMPLIANCE / AWS Security Audit"
        job_type: run
        inventory: "Demo Inventory"
        project: "Product Demos"
        playbook: "linux/insights_compliance_scan.yml"
        survey_enabled: true 
        survey_spec: "{{ lookup('ansible.builtin.template', 'template/survey_example.json') }}"
        
    - name: test output
      ansible.builtin.debug:
        msg: "{{ query('ansible.builtin.template', 'template/survey_example.json') }}"
