---
- name: Testing output of the json inventory query
  hosts: localhost
  gather_facts: false

  tasks: 
    - name: Print output
      ansible.builtin.debug: 
        msg: "{{ lookup('ansible.builtin.template', 'template/survey_example.json') }}"

    - name: setting group list fact
      ansible.builtin.set_fact:
        audit_list: "{{ groups['audit'] | unique | join('\n') }}"

    - name: Print output of groups
      ansible.builtin.debug: 
        msg: "{{ audit_list }}"
