---
- name: Testing output of the json inventory query
  hosts: localhost
  gather_facts: false

  tasks: 
    - name: Print output
      ansible.builtin.debug: 
        msg: "{{ lookup('ansible.builtin.template', 'template/survey_example.json') }}"

    - name: Print output of groups
      ansible.builtin.debug: 
        msg: "{{ groups['audit'] | unique | join('\n') }}"
